### PR TITLE
better UI for ModManagerActivity

### PR DESCRIPTION
**Pull request by achcyano**
new UI for MonManagerActivity,use new feature of Android develop (kotlin and databinding).

### CODE REVIEW

**Comment by achcyano** [comment]
screenshot

**Comment by artdeell** [comment]
No. You literally rewrote it in Kotlin. Hell no.

**Comment by achcyano** [comment]
> No. You literally rewrote it in Kotlin. Hell no.

have remove kotlin files in latest commit

**Comment by RomanChamelo** [comment]
> have remove kotlin files in latest commit

wait maks. since he didn't play Game anymore (retired)

**Comment by RomanChamelo** [comment]
> have remove kotlin files in latest commit

wait maks. since he didn't play game anymore

**Pull request merged**
